- course: "COMP34312 : Mathematical Topics in Machine Learning"
  role: "Teaching Assistant"
  institution: "University of Manchester"
  term: "Spring 2025"
  description: "Guide students through problem sets."

- course: "COMP64102 : Reasoning and Learning under Uncertainty"
  role: "Teaching Assistant"
  institution: "University of Manchester"
  term: "Spring 2025"
  description: "Helped create exams, and guided students through problem sets."

- course: "COMP61021 : Representation Learning"
  role: "Teaching Assistant"
  institution: "University of Manchester"
  term: "Fall 2024"
  description: "Helped create exams, and guided students through problem sets."
