# - course: "Represntation Learning"
#   role: "Teaching Assisstant"
#   institution: "University of Manchester"
#   term: "Fall 2024"
#   description: "Helped create exams, and guided students through problem sets."

- course: "COMP61021 : Representation Learning"
  role: "Teaching Assisstant"
  institution: "University of Manchester"
  term: "Fall 2024"
  description: "Helped create exams, and guided students through problem sets."
